'use client';

import React, { useState } from 'react';

const FAQItem = ({ question, answer }: { question: string; answer: string }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="border-b border-gray-200 py-4">
      <button
        className="flex justify-between items-center w-full text-left font-semibold text-lg text-gray-800 focus:outline-none"
        onClick={() => setIsOpen(!isOpen)}
      >
        {question}
        <svg
          className={`w-5 h-5 transform transition-transform ${isOpen ? 'rotate-180' : ''}`}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      {isOpen && <p className="mt-2 text-gray-600">{answer}</p>}
    </div>
  );
};

const FAQSection: React.FC = () => {
  return (
    <section id="faq" className="py-16 bg-gray-50">
      <div className="container mx-auto px-4">
        <h2 className="text-4xl font-bold text-center mb-12">Frequently Asked Questions About <span className="text-purple-600">Seedream</span></h2>
        <div className="max-w-3xl mx-auto space-y-6">
          <div className="border rounded-lg p-6 shadow-sm bg-white">
            <h3 className="text-2xl font-semibold mb-3">What kind of images can I create with Seedream?</h3>
            <p>With Seedream, you can create a vast array of images, from realistic photographs and digital paintings to abstract art and fantastical scenes. Our AI is versatile and can interpret a wide range of textual prompts. The only limit is your imagination when using Seedream.</p>
          </div>

          <div className="border rounded-lg p-6 shadow-sm bg-white">
            <h3 className="text-2xl font-semibold mb-3">Do I need any artistic skills to use Seedream?</h3>
            <p>Absolutely not! Seedream is designed for everyone. Whether you're a seasoned artist or a complete beginner, our intuitive interface and powerful AI make it easy to generate stunning visuals without any prior artistic experience. Just describe your vision to Seedream.</p>
          </div>

          <div className="border rounded-lg p-6 shadow-sm bg-white">
            <h3 className="text-2xl font-semibold mb-3">How long does it take to generate an image with Seedream?</h3>
            <p>Image generation with Seedream is incredibly fast. Most images are created within seconds, allowing for quick iteration and exploration of your creative ideas. Experience rapid creation with Seedream.</p>
          </div>

          <div className="border rounded-lg p-6 shadow-sm bg-white">
            <h3 className="text-2xl font-semibold mb-3">Can I use the images generated by Seedream for commercial purposes?</h3>
            <p>Yes, images generated by Seedream are typically free for commercial use, depending on the specific licensing terms of the underlying AI models and our platform's policy. Please refer to our terms of service for detailed information regarding commercial usage rights for Seedream creations.</p>
          </div>

          <div className="border rounded-lg p-6 shadow-sm bg-white">
            <h3 className="text-2xl font-semibold mb-3">What makes Seedream different from other AI image generators?</h3>
            <p>Seedream focuses on a seamless user experience, high-quality output, and continuous innovation. We strive to provide a platform that is both powerful and accessible, making AI art creation enjoyable and efficient for all users. Discover the unique advantages of Seedream.</p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FAQSection;