// ... existing code ...

const WhyChooseSeedream: React.FC = () => {
  return (
    <section id="why" className="py-16 bg-white">
      <div className="container mx-auto px-4">
        <h2 className="text-4xl font-bold text-center mb-12">Why Choose <span className="text-purple-600">Seedream</span>? Unmatched AI Art Creation</h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-5xl mx-auto">
          <div className="p-6 border rounded-lg shadow-md">
            <h3 className="text-2xl font-semibold mb-4">Effortless Creation with Seedream</h3>
            <p>Seedream simplifies the complex process of AI image generation. Our user-friendly interface ensures that anyone, regardless of their technical expertise, can create stunning visuals with just a few clicks. No coding, no intricate settings – just pure creativity with Seedream.</p>
          </div>
          <div className="p-6 border rounded-lg shadow-md">
            <h3 className="text-2xl font-semibold mb-4">High-Quality Outputs from Seedream AI</h3>
            <p>We pride ourselves on the exceptional quality of images generated by Seedream. Our advanced AI models produce high-resolution, detailed, and aesthetically pleasing artwork that meets professional standards. Experience the difference with Seedream's superior image fidelity.</p>
          </div>
          <div className="p-6 border rounded-lg shadow-md">
            <h3 className="text-2xl font-semibold mb-4">Speed and Efficiency with Seedream</h3>
            <p>Time is precious, and Seedream respects that. Our optimized infrastructure ensures rapid image generation, allowing you to iterate on your ideas quickly and efficiently. Get your creative results faster with Seedream.</p>
          </div>
          <div className="p-6 border rounded-lg shadow-md">
            <h3 className="text-2xl font-semibold mb-4">Versatile Styles and Options in Seedream</h3>
            <p>From photorealistic renders to abstract art, Seedream offers a wide array of styles and customization options. Explore different artistic directions and find the perfect visual for your project. The creative possibilities with Seedream are endless.</p>
          </div>
          <div className="p-6 border rounded-lg shadow-md">
            <h3 className="text-2xl font-semibold mb-4">Community and Support for Seedream Users</h3>
            <p>Join a growing community of creators using Seedream. Share your art, get inspiration, and receive support from our dedicated team. We are committed to fostering a vibrant ecosystem around Seedream.</p>
          </div>
          <div className="p-6 border rounded-lg shadow-md">
            <h3 className="text-2xl font-semibold mb-4">Continuous Innovation at Seedream</h3>
            <p>The world of AI is constantly evolving, and so is Seedream. We are dedicated to continuous research and development, bringing you the latest features and improvements to enhance your AI art generation experience with Seedream.</p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default WhyChooseSeedream;